pub mod camera;
pub mod canvas;
pub mod color;
pub mod intersection;
pub mod light;
pub mod material;
pub mod math;
pub mod misc;
pub mod pattern;
pub mod ray;
pub mod shape;
pub mod world;
// use examples::{chapter_11, chapter_12, chapter_13, chapter_14};
pub mod obj;
